name: Deploy Next.js App to Windows Laptop

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install  # or yarn install

      - name: Build Next.js App
        run: npm run build  # Generates the .next folder

      - name: Deploy to Windows Laptop via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WINDOWS_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r .next/ Sahil@192.168.1.10:/C/Users/Sahil/next-app
          ssh -o StrictHostKeyChecking=no -i private_key.pem Sahil@192.168.1.10 << 'EOF'
            cd C:/Users/YourUser/next-app
            pm2 restart all || pm2 start npm --name "next-app" -- run start
          EOF
