name: Deploy React App

on:
  push:
    branches:
      - main  # Change if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -r build ubuntu@your-ec2-ip:/home/ubuntu/react-app
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@your-ec2-ip << 'EOF'
            cd /home/ubuntu/react-app
            pm2 restart all || pm2 start npm --name "react-app" -- start
          EOF
